apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
spec:
  destination:
    namespace: infra-tools
    server: https://kubernetes.default.svc
  project: mlops
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: minio
    targetRevision: 13.7.2
    helm:
      valuesObject:
        auth:
          rootUser: minio
          rootPassword: minio123
        defaultBuckets: mlflow-artifacts
        service:
          type: ClusterIP
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
