apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: infra-tools
spec:
  project: default
  destination:
    namespace: mlflow
    server: https://kubernetes.default.svc
  source:
    repoURL: https://community-charts.github.io/helm-charts
    chart: mlflow
    targetRevision: 1.6.2
    helm:
      valuesObject:
        image:
          repository: mlflow/mlflow
          tag: 2.22.2

        # Install psycopg2 on top of the MLflow image
        command: ["/bin/bash"]
        args:
          - -c
          - |
            pip install psycopg2-binary
            exec mlflow server \
              --backend-store-uri postgresql://mlflow:mlflowpass@mlflow-postgres.mlflow.svc.cluster.local:5432/mlflow \
              --default-artifact-root s3://mlflow-artifacts \
              --host 0.0.0.0 \
              --port 5000

        backendStore:
          postgres:
            enabled: true
            host: mlflow-postgres.mlflow.svc.cluster.local
            port: 5432
            database: mlflow
            user: mlflow
            password: mlflowpass

        artifactRoot:
          s3:
            enabled: true
            bucket: mlflow-artifacts
            awsAccessKeyId: minio
            awsSecretAccessKey: minio123

        service:
          type: ClusterIP
          port: 5000

        extraEnvVars:
          MLFLOW_S3_ENDPOINT_URL: http://minio.mlflow.svc.cluster.local:9000
          AWS_ACCESS_KEY_ID: minio
          AWS_SECRET_ACCESS_KEY: minio123
          AWS_REGION: us-east-1

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
