apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: infra-tools
spec:
  project: default
  destination:
    namespace: mlflow
    server: https://kubernetes.default.svc
  source:
    repoURL: https://community-charts.github.io/helm-charts
    chart: mlflow
    targetRevision: 0.8.4
    helm:
      valuesObject:
        image:
          repository: ghcr.io/mlflow/mlflow
          tag: 2.10.0

        backendStore:
          database: postgresql
          postgres:
            host: mlflow-postgres.mlflow.svc.cluster.local
            port: 5432
            database: mlflow
            user: mlflow
            password: mlflowpass

        artifactStore:
          defaultArtifactRoot: s3://mlflow-artifacts
          s3:
            endpointUrl: http://minio.mlflow.svc.cluster.local:9000
            bucketName: mlflow-artifacts
            accessKey: minio
            secretKey: minio123

        service:
          type: ClusterIP
          port: 5000
          
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
