apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: infra-tools
spec:
  project: default
  source:
    repoURL: https://github.com/bitnami/charts
    targetRevision: main
    path: bitnami/mlflow
    helm:
      releaseName: mlflow
      parameters:
        - name: service.type
          value: ClusterIP
        - name: service.port
          value: "5000"
        - name: resources.requests.memory
          value: 256Mi
        - name: resources.requests.cpu
          value: 100m
  destination:
    namespace: mlflow
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}
