apiVersion: v1
kind: Secret
metadata:
  name: mlflow-secrets
  namespace: mlflow
type: Opaque
stringData:
  MLFLOW_S3_ENDPOINT_URL: http://minio.mlflow.svc.cluster.local:9000
  AWS_ACCESS_KEY_ID: minio
  AWS_SECRET_ACCESS_KEY: minio123
  MLFLOW_BACKEND_STORE_URI: postgresql://mlflow:mlflow123@postgres-postgresql.mlflow.svc.cluster.local:5432/mlflow
