apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: infra-tools
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 15.5.12
    helm:
      releaseName: postgres
      parameters:
        - name: auth.database
          value: mlflow
        - name: auth.username
          value: mlflow
        - name: auth.password
          value: mlflow123
        - name: resources.requests.memory
          value: 256Mi
        - name: resources.requests.cpu
          value: 100m
  destination:
    namespace: mlflow
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}
