apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow-postgres
spec:
  destination:
    namespace: infra-tools
    server: https://kubernetes.default.svc
  project: mlops
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 12.5.6
    helm:
      valuesObject:
        auth:
          username: mlflow
          password: mlflowpass
          database: mlflow
        primary:
          persistence:
            enabled: true
            size: 1Gi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
